### PR TITLE
Add env to allow custom backup options

### PR DESCRIPTION
**Pull request by pepijn-vanvlaanderen**
Make it easy to add custom backup options, for example if one wants to exclude specific table (data).

### CODE REVIEW

**Comment by brody192** [comment]
What backup options would be needed here? this seems like it has a lot of potential to break backups.

**Comment by pepijn-vanvlaanderen** [comment]
Like any of the pg_dump options that are possible, so for my use case it was excluding specific tables. But different export format or specifying only to include specific tables could be useful as well.

Obviously if misconfigured it can break.

**Comment by brody192** [comment]
Makes sense, thanks for the explanation.

Think you can update the README too?

**Comment by pepijn-vanvlaanderen** [comment]
@brody192 sure thing, I have updated the PR.

**Pull request merged**
